#!/bin/bash

function build_module_pages() {
	# identifier is a unique identifier for the set of modules being processed
	# its used as a suffix for the history file and passed to the new_add_modules php script 
	# were it is used to determine the correct field in drupal
	identifier=$1
	modpath=$2

	moduleshistory="/usr/share/drupal7/sites/default/files/moduleshistory-${identifier}"
	touch $moduleshistory
#Create the temporary files
	modulesupdate=`mktemp`
	sorted=`mktemp`
	modulefiles=`mktemp`
	changedmodules=`mktemp`

# Get modules for the current thing
	export MODULEPATH=$modpath
	modulecmd bash av -t &> $modulefiles

# Fix up the file to get a clean list of the modules and versions
	sed -i -e "1d" $modulefiles
	sed -i 's/(default)//' $modulefiles

# Compare with the last run to get additions and deletions
	comm -3 --nocheck-order $modulefiles $moduleshistory > $modulesupdate

# Strip out the version numbers and remove the tabs in the file
# we dont care if something has been removed or added just that it *changed*
	cut -d "/" -f 1 $modulesupdate | sed -e 's/^[ \t]*//'| sort | uniq > $sorted

# Reads the previous created file for the modules listed and gets the list of modules and versions from the o
riginal file
# Note this wont cope with removing the last version of a piece of software
	while read line
	do
		grep "^$line/" $modulefiles >> $changedmodules
	done < $sorted

# Copy the current file over the history file for the next run
	cp $modulefiles $moduleshistory

# Run script to add modules 
	php /usr/share/drupal7/new_add_modules.php $identifier $changedmodules

# Append modules to the running list of modules
	cat $modulefiles | cut -d "/" -f1 | uniq >> $moduleslist
	
	# Clean up the temporary files
	rm $sorted
	rm $changedmodules
	rm $modulesupdate
	rm $modulefiles
}
# Suppresses warning from drupal
export REMOTE_ADDR="127.0.0.1"

moduleslist=`mktemp`
#build_module_pages 'rhel6' '/mnt/rhel6-modules'
build_module_pages 'rhel7' '/mnt/rhel7-modules'
build_module_pages 'rhel7-gpu' '/mnt/rhel7-gpu-modules'

sortedmoduleslist=`mktemp`
sort -u < $moduleslist > $sortedmoduleslist

php /usr/share/drupal7/add_modules_page.php ${sortedmoduleslist} > /dev/null

rm ${moduleslist} ${sortedmoduleslist}

